minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: "علی موسوی خرد" # the main title
subtitle: "محتوای برنامه‌نویسی به زبان فارسی" # it will display as the sub-title
description: >- # used by seo meta and the atom feed
  Ali Mousavi Kherad personal weblog about programming.

name: Ali Mousavi Kherad
author: Ali Mousavi Kherad
url: "https://amkherad.ir"
repository: amkherad/amkherad.github.io
logo: /assets/img/avatar.jpg # support internet resources
# words_per_minute: 200
# masthead_title           : "Custom Title" # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)


lang: "fa"
locale: "fa"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Tehran
excerpt_separator: "<!--more-->"

# boolean type, global switch for ToC in posts.
toc: true
# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ""

# DO NOT change this unless you're a Pro user on Jekyll and Web development,
# or you think you're smart enough to change other relevant URLs within this template.
permalink: /blog/:categories/:title/
paginate: 10
paginate_path: /page:num/
markdown: kramdown
highlighter: rouge


github:
  username: amkherad # change to your github username

twitter:
  username: amkherad # change to your twitter username


social:
  name: Ali Mousavi Kherad # it will shows as the copyright owner in Footer
  email: alimousavikherad@outlook.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/amkherad # change to your twitter homepage
    - https://github.com/amkherad # change to your github homepage
    # Uncomment below to add more social links
    - https://www.facebook.com/username
    - https://www.linkedin.com/in/username

google_site_verification: google_meta_tag_verification # change to your verification string

#--------------------------

addons:
  - plugins

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

google_analytics:
  id: "UA-176003281-1" # Fill with your Google Analytics ID
  pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ""
    proxy_endpoint: ""
    cache: false # pv data local cache, good for the users from GFW area.

disqus:
  comments: true # boolean type, the global switch for posts comments.
  shortname: "amkherad-ir" # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# Prefer color scheme setting, available values:
#
#     dual   - Follow the system prefer color by default, and a toggle will display
#              in the left bottom of Sidebar, which used for switch the theme between dark and light.
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
# theme_mode: dark

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: "highlight"
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: true
      share: true
  # _pets
  - scope:
      path: ""
      type: pets
    values:
      layout: single
      author_profile: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

sass:
  sass_dir: /assets/css
  style: compressed

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

include:
  - .htaccess
  - _pages
exclude:
  - vendor # Avoid Jekyll mistakenly read the vendor directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE

sitemap_exclude: # Sitemap will exclude the following items.
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
    - "*.sublime-project"
    - "*.sublime-workspace"
    - vendor
    - .asset-cache
    - .bundle
    - .jekyll-assets-cache
    - .sass-cache
    - assets/js/plugins
    - assets/js/_main.js
    - assets/js/vendor
    - Capfile
    - CHANGELOG
    - config
    - Gemfile
    - Gruntfile.js
    - gulpfile.js
    - LICENSE
    - log
    - node_modules
    - package.json
    - Rakefile
    - README
    - tmp
keep_files:
  - .git
  - .svn
